![](../docs/banner.png)

# NumPy


## Exercises

### 1.

Import numpy under the alias `np`.

In [2]:
# Your answer here.
import numpy as np

### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [ ]:
# Your answer here.
five_zero = np.zeros(5)
print("this is an array of 5 zeros:",five_zero)
ten_ones = np.ones(10)
print("this is an array of 10 ones:",ten_ones)
full_array = np.full((3,3),52.141)
print("this is an array of 53.141s :",full_array)
integers = np.arange(21)
print("this is an array of integers 1 to 20:",integers)
matrix = np.ones((5,5))
print(matrix)

this is an array of 5 zeros: [0. 0. 0. 0. 0.]
this is an array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
this is an array of 53.141s : [[52.141 52.141 52.141]
 [52.141 52.141 52.141]
 [52.141 52.141 52.141]]
this is an array of integers 1 to 20: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [ ]:
# Your answer here.

a = np.random.randn(3,3,3)
b= a.reshape(27)
b

array([ 2.71870109, -0.26965544,  1.98877483,  0.32947746,  1.57272142,
        0.9711901 ,  0.35891355,  1.05495392,  0.55436068, -0.54765225,
        1.05783853, -0.14976577, -0.09805502, -2.2728271 ,  0.51000412,
       -1.8966798 , -0.16672623, -0.59724922, -1.30642299, -0.36803614,
        1.79588982, -0.11361812, -2.00143095, -1.28597248, -0.98302828,
        0.14162646, -1.60035346])

### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [3]:
# Your answer here.
numbers = np.linspace(1, 10, 20)
numbers

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [4]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```python
20
```

In [ ]:
# Your answer here.
a[3,4]

20

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [ ]:
# Your answer here.
a[1:,3:]


array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Your answer here.
a[1]

array([ 6,  7,  8,  9, 10])

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [ ]:
# Your answer here.
a[2:4,:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

```python
array([[ 8,  9],
       [13, 14]])
```

In [ ]:
# Your answer here.
a
a[1:3,2:4]



array([[ 8,  9],
       [13, 14]])

### 6.

Calculate the sum of all the numbers in `a`.

In [ ]:
# Your answer here.
print(a.sum())

325


### 7.

Calculate the sum of each row in `a`.

In [6]:
# Your answer here.
a.sum(axis = 1)

array([ 15,  40,  65,  90, 115])

### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Your answer here.
print (a.mean())
grt_mean = a > a.mean()
print(a[grt_mean])

13.0
[14 15 16 17 18 19 20 21 22 23 24 25]


### 9.

Find the location of the minimum value in the following array `b`:

In [ ]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [ ]:
# Your answer here.
min = b.argmin()
min

6

### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [ ]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [ ]:
# Your answer here.
max = c.argmax()
max

5

<hr>
<hr>
<hr>